countrynside_site_homepage:
    path: /
    defaults: { _controller: CountrynsideSiteBundle:Default:index }
    
countrynside_site_connexion:
    path: /connexion
    defaults: { _controller: CountrynsideSiteBundle:Default:connexion }
    
countrynside_site_annonce:
    path: /user/annonce
    defaults: { _controller: CountrynsideSiteBundle:Default:annonce }
    
countrynside_site_mes_annonces:
    path: /user/mes_annonces
    defaults: { _controller: CountrynsideSiteBundle:Default:mesAnnonces }